from pathlib import Path

path=Path('tools/ars_gameplay_polish.py')
text=path.read_text()

def swap(old,new,label):
    global text
    if text.count(old)!=1: raise SystemExit(f'{label}: expected 1, found {text.count(old)}')
    text=text.replace(old,new,1)

old="old_find_port = \"function findPortApproach(city){const portIce=portIceInfo(city),center=polar(city.lat,city.lon);let best=null,bestDistance=Infinity;for(let radius=2;radius<=68;radius+=2)for(let i=0;i<48;i++){const a=i*Math.PI/24,x=center.x+Math.cos(a)*radius,y=center.y+Math.sin(a)*radius,pos=unpolar(x,y);if(pos.lat<MIN_LAT||isLand(x,y))continue;const profile=iceNavigationProfileAt(x,y);if(!profile.allowed)continue;const distance=Math.hypot(x-state.x,y-state.y);if(distance<bestDistance){best={x,y,shoreDistance:radius,ice:portIce};bestDistance=distance;}}return best;}\""
new="old_find_port = \"function findPortApproach(city){const portIce=portIceInfo(city);if(!portIce.navigationAllowed)return null;const center=polar(city.lat,city.lon);for(let radius=2;radius<=68;radius+=2){let best=null,bestDistance=Infinity;for(let i=0;i<48;i++){const a=i*Math.PI/24,x=center.x+Math.cos(a)*radius,y=center.y+Math.sin(a)*radius,pos=unpolar(x,y);if(pos.lat<MIN_LAT||isBlocked(x,y)||!iceNavigationProfileAt(x,y).allowed)continue;const distance=Math.hypot(x-state.x,y-state.y);if(distance<bestDistance){best={x,y,shoreDistance:radius};bestDistance=distance;}}if(best)return best;}return null;}\""
swap(old,new,'port matcher assignment')

old="new_find_port = \"function findPortApproach(city){const portIce=portIceInfo(city),center=polar(city.lat,city.lon);let reachable=null,reachableScore=Infinity,fallback=null,fallbackDistance=Infinity;for(let radius=2;radius<=82;radius+=2)for(let i=0;i<72;i++){const a=i*Math.PI/36,x=center.x+Math.cos(a)*radius,y=center.y+Math.sin(a)*radius,pos=unpolar(x,y);if(pos.lat<MIN_LAT||isLand(x,y))continue;const profile=iceNavigationProfileAt(x,y);if(!profile.allowed)continue;const distance=Math.hypot(x-state.x,y-state.y);if(distance<fallbackDistance){fallback={x,y,shoreDistance:radius,ice:portIce};fallbackDistance=distance;}if(clearDisplacement(state.x,state.y,x,y)){const score=distance+radius*.28;if(score<reachableScore){reachable={x,y,shoreDistance:radius,ice:portIce};reachableScore=score;}}}return reachable||fallback;}\""
new="new_find_port = \"function findPortApproach(city){const portIce=portIceInfo(city);if(!portIce.navigationAllowed)return null;const center=polar(city.lat,city.lon);let reachable=null,reachableScore=Infinity,fallback=null,fallbackDistance=Infinity;for(let radius=2;radius<=82;radius+=2)for(let i=0;i<72;i++){const a=i*Math.PI/36,x=center.x+Math.cos(a)*radius,y=center.y+Math.sin(a)*radius,pos=unpolar(x,y);if(pos.lat<MIN_LAT||isBlocked(x,y)||!iceNavigationProfileAt(x,y).allowed)continue;const distance=Math.hypot(x-state.x,y-state.y);if(distance<fallbackDistance){fallback={x,y,shoreDistance:radius};fallbackDistance=distance;}if(clearDisplacement(state.x,state.y,x,y)){const score=distance+radius*.28;if(score<reachableScore){reachable={x,y,shoreDistance:radius};reachableScore=score;}}}return reachable||fallback;}\""
swap(old,new,'new port assignment')

old='game = replace_once(game, "resetDistantWildlifeFromPort(city);research?.enterPort?.(city);", "research?.enterPort?.(city);", \'do not recycle observed wildlife\')'
new='game = replace_once(game, "currentPortCity=city;resetDistantWildlifeFromPort(city);if(state.started)", "currentPortCity=city;if(state.started)", \'do not recycle observed wildlife\')'
swap(old,new,'wildlife reset matcher')

old="old_end = \"function endGame(title,message){if(state.gameOver)return;state.gameOver=true;state.moving=false;state.commandActive=false;state.ramming=false;state.tx=state.x;state.ty=state.y;research?.leavePort?.();ui.gameOverTitle.textContent=title;ui.gameOverMessage.textContent=message;ui.gameOver.classList.remove('hidden');ui.resourceWarning?.classList.remove('show');sound.play('paper-rejected');}\""
new="old_end = \"function endGame(title,message){if(state.gameOver)return;state.gameOver=true;state.moving=false;state.tx=state.x;state.ty=state.y;clearTimeout(toastTimer);ui.toast.classList.remove('show','frozen');ui.gameOverTitle.textContent=title;ui.gameOverMessage.textContent=message;ui.gameOver.classList.remove('hidden');analytics.track('game_over',{game_over_reason:title||'',game_over_message:message||''});}\""
swap(old,new,'end game matcher')

old="new_end = \"function endGame(title,message){if(state.gameOver)return;state.gameOver=true;state.moving=false;state.commandActive=false;state.ramming=false;state.tx=state.x;state.ty=state.y;research?.leavePort?.();ui.gameOverTitle.textContent=title;ui.gameOverMessage.textContent=message;let image=ui.gameOver.querySelector('.failure-scientist');if(!image){image=document.createElement('img');image.className='failure-scientist';image.style.cssText='display:block;width:92px;height:92px;margin:12px auto;border-radius:50%;object-fit:cover;border:2px solid rgba(255,255,255,.55);box-shadow:0 8px 24px rgba(0,0,0,.32)';ui.gameOver.insertBefore(image,ui.gameOverMessage);}const chief=research?.getState?.()?.scientists?.find(item=>item.isPlayer)||research?.getState?.()?.scientists?.[0];image.src=chief?.portrait||'assets/scientists/maya-chen.webp';image.alt=title==='OUT OF FOOD'?'Hungry Chief Scientist':'Cold Chief Scientist';image.style.filter=title==='OUT OF FOOD'?'sepia(.35) saturate(.7) brightness(.78)':'grayscale(.35) hue-rotate(145deg) saturate(.75) brightness(.8)';ui.gameOver.classList.remove('hidden');ui.resourceWarning?.classList.remove('show');sound.play('paper-rejected');}\""
new="new_end = \"function endGame(title,message){if(state.gameOver)return;state.gameOver=true;state.moving=false;state.tx=state.x;state.ty=state.y;clearTimeout(toastTimer);ui.toast.classList.remove('show','frozen');ui.gameOverTitle.textContent=title;ui.gameOverMessage.textContent=message;let image=ui.gameOver.querySelector('.failure-scientist');if(!image){image=document.createElement('img');image.className='failure-scientist';image.style.cssText='display:block;width:92px;height:92px;margin:12px auto;border-radius:50%;object-fit:cover;border:2px solid rgba(255,255,255,.55);box-shadow:0 8px 24px rgba(0,0,0,.32)';ui.gameOver.insertBefore(image,ui.gameOverMessage);}const rs=research?.getState?.(),chief=rs?.scientists?.find(item=>item.isPlayer)||rs?.scientists?.[0];image.src=chief?.portrait||'assets/scientists/maya-chen.webp';image.alt=title==='OUT OF FOOD'?'Hungry Chief Scientist':'Cold Chief Scientist';image.style.filter=title==='OUT OF FOOD'?'sepia(.35) saturate(.7) brightness(.78)':'grayscale(.35) hue-rotate(145deg) saturate(.75) brightness(.8)';ui.gameOver.classList.remove('hidden');analytics.track('game_over',{game_over_reason:title||'',game_over_message:message||''});}\""
swap(old,new,'end game replacement')

path.write_text(text)
