from pathlib import Path

path=Path('tools/ars_gameplay_polish.py')
text=path.read_text()
old="old_find_port = \"function findPortApproach(city){const portIce=portIceInfo(city),center=polar(city.lat,city.lon);let best=null,bestDistance=Infinity;for(let radius=2;radius<=68;radius+=2)for(let i=0;i<48;i++){const a=i*Math.PI/24,x=center.x+Math.cos(a)*radius,y=center.y+Math.sin(a)*radius,pos=unpolar(x,y);if(pos.lat<MIN_LAT||isLand(x,y))continue;const profile=iceNavigationProfileAt(x,y);if(!profile.allowed)continue;const distance=Math.hypot(x-state.x,y-state.y);if(distance<bestDistance){best={x,y,shoreDistance:radius,ice:portIce};bestDistance=distance;}}return best;}\""
new="old_find_port = \"function findPortApproach(city){const portIce=portIceInfo(city);if(!portIce.navigationAllowed)return null;const center=polar(city.lat,city.lon);for(let radius=2;radius<=68;radius+=2){let best=null,bestDistance=Infinity;for(let i=0;i<48;i++){const a=i*Math.PI/24,x=center.x+Math.cos(a)*radius,y=center.y+Math.sin(a)*radius,pos=unpolar(x,y);if(pos.lat<MIN_LAT||isBlocked(x,y)||!iceNavigationProfileAt(x,y).allowed)continue;const distance=Math.hypot(x-state.x,y-state.y);if(distance<bestDistance){best={x,y,shoreDistance:radius};bestDistance=distance;}}if(best)return best;}return null;}\""
if text.count(old)!=1: raise SystemExit(f'port matcher assignment: expected 1, found {text.count(old)}')
text=text.replace(old,new,1)
old2="new_find_port = \"function findPortApproach(city){const portIce=portIceInfo(city),center=polar(city.lat,city.lon);let reachable=null,reachableScore=Infinity,fallback=null,fallbackDistance=Infinity;for(let radius=2;radius<=82;radius+=2)for(let i=0;i<72;i++){const a=i*Math.PI/36,x=center.x+Math.cos(a)*radius,y=center.y+Math.sin(a)*radius,pos=unpolar(x,y);if(pos.lat<MIN_LAT||isLand(x,y))continue;const profile=iceNavigationProfileAt(x,y);if(!profile.allowed)continue;const distance=Math.hypot(x-state.x,y-state.y);if(distance<fallbackDistance){fallback={x,y,shoreDistance:radius,ice:portIce};fallbackDistance=distance;}if(clearDisplacement(state.x,state.y,x,y)){const score=distance+radius*.28;if(score<reachableScore){reachable={x,y,shoreDistance:radius,ice:portIce};reachableScore=score;}}}return reachable||fallback;}\""
new2="new_find_port = \"function findPortApproach(city){const portIce=portIceInfo(city);if(!portIce.navigationAllowed)return null;const center=polar(city.lat,city.lon);let reachable=null,reachableScore=Infinity,fallback=null,fallbackDistance=Infinity;for(let radius=2;radius<=82;radius+=2)for(let i=0;i<72;i++){const a=i*Math.PI/36,x=center.x+Math.cos(a)*radius,y=center.y+Math.sin(a)*radius,pos=unpolar(x,y);if(pos.lat<MIN_LAT||isBlocked(x,y)||!iceNavigationProfileAt(x,y).allowed)continue;const distance=Math.hypot(x-state.x,y-state.y);if(distance<fallbackDistance){fallback={x,y,shoreDistance:radius};fallbackDistance=distance;}if(clearDisplacement(state.x,state.y,x,y)){const score=distance+radius*.28;if(score<reachableScore){reachable={x,y,shoreDistance:radius};reachableScore=score;}}}return reachable||fallback;}\""
if text.count(old2)!=1: raise SystemExit(f'new port assignment: expected 1, found {text.count(old2)}')
path.write_text(text.replace(old2,new2,1))
